[book]
authors = ["Jorge Dominguez"]
language = "es"
multilingual = true
src = "src"
title = "Creando juegos con DragonRuby"
description = "Un libro gratuito sobre creación de juegos 2D con DragonRuby Game Toolkit."

[output.html]
git-repository-url = "https://github.com/DragonRidersUnite/book"

[output.html.print]
enable = false
